
services:
  r:
    container_name: r-arm64
    build:
      context: .
    volumes:
      - .:/workspace
    tty: true
    #environment:
    #  PASSWORD: passwd
    #ports:
    #  - "8080:8787"
    #cpu_quota: 50000
    #mem_limit: 9g
